[package]
name = "rust-with-slint-app"
version = "0.1.0"
authors = ["Evan <evan.perreau@gmail.com>"]
edition = "2021"
build = "build.rs"

[dependencies]
slint = "1.4"

[build-dependencies]
slint-build = "1.4"
